### ISSUE TITLE
rm: cannot remove '**/nekoray.desktop': No such file or directory

### ISSUE THREAD

**Issue by MhKh78** [ohmydevops/nekoray-installer#1]
if user has not previously installed nekoray there will not be any nekoray.desktop file and using rm directly will crash the installer

so, need to create nekoray.desktop entry if it does not exist, then remove it (a work around to create an empty file and making sure installer won't crash is just simply using touch before rm)

**Comment by ohmydevops** [comment]
I have merged your pull request
